# Generated by Django 4.1.1 on 2022-09-26 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.label'),
        ),
    ]
