# Generated by Django 4.1.1 on 2022-09-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='short_title',
        ),
    ]
